# Generated by Django 5.2.4 on 2025-08-04 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icfes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='icfes.subject')),
            ],
            options={
                'ordering': ['subject__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('explanation', models.TextField()),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('web', 'Página Web'), ('image', 'Imagen'), ('pdf', 'PDF'), ('note', 'Apunte')], max_length=10)),
                ('link', models.URLField()),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='study.subtopic')),
            ],
            options={
                'ordering': ['subtopic__subject__name', 'subtopic__name', 'title'],
            },
        ),
    ]
